# Generated by Django 4.2 on 2023-10-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_puntoreposicion_registroalertasstock_delete_alerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coccion',
            fields=[
                ('idcoccion', models.AutoField(db_column='idCoccion', primary_key=True, serialize=False)),
                ('fechacoccion', models.DateField(db_column='fechaCoccion')),
                ('volumenproducido', models.DecimalField(db_column='volumenProducido', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'coccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('idreceta', models.IntegerField(db_column='idReceta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'receta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AuthGroup',
        ),
        migrations.DeleteModel(
            name='AuthGroupPermissions',
        ),
        migrations.DeleteModel(
            name='AuthPermission',
        ),
        migrations.DeleteModel(
            name='AuthtokenToken',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
        migrations.DeleteModel(
            name='AuthUserGroups',
        ),
        migrations.DeleteModel(
            name='AuthUserUserPermissions',
        ),
        migrations.DeleteModel(
            name='DjangoAdminLog',
        ),
        migrations.DeleteModel(
            name='DjangoContentType',
        ),
        migrations.DeleteModel(
            name='DjangoMigrations',
        ),
        migrations.DeleteModel(
            name='DjangoSession',
        ),
        migrations.DeleteModel(
            name='PuntoReposicion',
        ),
        migrations.DeleteModel(
            name='Recetas',
        ),
        migrations.DeleteModel(
            name='RegistroAlertasStock',
        ),
    ]
